spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    master:
      url: ${jdbc.url.master}
      username: ${jdbc.username.master}
      password: ${jdbc.password.master}
      driver-class-name: ${jdbc.driverClassName.master}
    slave:
      driver-class-name: ${jdbc.driverClassName.slave}
      url: ${jdbc.url.slave}
      username: ${jdbc.username.slave}
      password: ${jdbc.password.slave}
  redis:
    port: 6379
    host: 127.0.0.1


mybatis:
  mapper-locations: classpath:base/mapper/*Mapper.xml