spring:
  shardingsphere:
    datasource:
      names: m0,m1
      m0:
        type: org.apache.commons.dbcp2.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/deng?rewriteBatchedStatements=true&useUnicode=true&&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root123456
      m1:
        type: org.apache.commons.dbcp2.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/hu?rewriteBatchedStatements=true&useUnicode=true&&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root123456
    props:
      sql:
        show: true
mybatis-plus:
  type-aliases-package: com.deng.shardingsphere.atomikos.xa.entity
  configuration:
    # 设置驼峰命名规则
    map-underscore-to-camel-case: true