spring:
  application:
    name: dtx-seata-tcc-order
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dtx_order?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123456
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

server:
  port: 56081


seata:
  application-id: ${spring.application.name}
  tx-service-group: SEATA_GROUP
  service:
    vgroup-mapping:
      SEATA_GROUP: default
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      application: seata-server
      namespace: public
      cluster: default
      group: SEATA_GROUP

