package com.deng.study.shardingsphere;

public class CreateTable {

    public static void main(String[] args) {
        String sourceDatabase = "order_new_db";
        String sourceTable = "t_order";
        String targetDatabase;
        String targetTable;

        for (Integer i = 11; i <= 15; i++) {
            if(i.toString().length() == 1){
                targetDatabase = sourceDatabase + "_0" + i;
            }else{
                targetDatabase = sourceDatabase + "_" + i;
            }

            for (Integer no = 0; no < 32; no++) {
                if (no.toString().length() == 1) {
                    targetTable = sourceTable + "_" + "000" + no.toString();
                } else if (no.toString().length() == 2) {
                    targetTable = sourceTable + "_" + "00" + no.toString();
                } else if (no.toString().length() == 3){
                    targetTable = sourceTable + "_" + "0" + no.toString();
                } else {
                    targetTable = sourceTable + "_" + no.toString();
                }
                String targetStr = "CREATE TABLE " + targetDatabase + "." + targetTable
//                        + " LIKE " + sourceDatabase + "." + sourceTable
                +"("
                        +  "id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',"
                        +  "order_no varchar(64) DEFAULT NULL COMMENT '订单号',"
                        +  "name varchar(64) DEFAULT NULL COMMENT '名称',"
                        +  "user_id bigint(20) DEFAULT NULL COMMENT '用户id',"
                        +  "status varchar(64) DEFAULT NULL COMMENT '状态',"
                        +  "create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',"
                        +  "update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',"
                        +  "PRIMARY KEY (id),"
                        +  "KEY idx_createTime (create_time) USING BTREE"
                        +") ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='"+targetTable+"';";

                System.out.println(targetStr);
            }
        }

//        CREATE TABLE order_new_db_10.t_order_0000(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0004';
//        CREATE TABLE order_new_db_10.t_order_0001(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0005';
//        CREATE TABLE order_new_db_10.t_order_0002(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0006';
//        CREATE TABLE order_new_db_10.t_order_0003(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0007';
//        CREATE TABLE order_new_db_10.t_order_0004(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0004';
//        CREATE TABLE order_new_db_10.t_order_0005(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0005';
//        CREATE TABLE order_new_db_10.t_order_0006(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0006';
//        CREATE TABLE order_new_db_10.t_order_0007(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0007';
//        CREATE TABLE order_new_db_10.t_order_0008(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0008';
//        CREATE TABLE order_new_db_10.t_order_0009(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0009';
//        CREATE TABLE order_new_db_10.t_order_0010(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0010';
//        CREATE TABLE order_new_db_10.t_order_0011(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0011';
//        CREATE TABLE order_new_db_10.t_order_0012(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0012';
//        CREATE TABLE order_new_db_10.t_order_0013(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0013';
//        CREATE TABLE order_new_db_10.t_order_0014(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0014';
//        CREATE TABLE order_new_db_10.t_order_0015(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0015';
//        CREATE TABLE order_new_db_10.t_order_0016(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0016';
//        CREATE TABLE order_new_db_10.t_order_0017(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0017';
//        CREATE TABLE order_new_db_10.t_order_0018(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0018';
//        CREATE TABLE order_new_db_10.t_order_0019(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0019';
//        CREATE TABLE order_new_db_10.t_order_0020(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0020';
//        CREATE TABLE order_new_db_10.t_order_0021(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0021';
//        CREATE TABLE order_new_db_10.t_order_0022(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0022';
//        CREATE TABLE order_new_db_10.t_order_0023(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0023';
//        CREATE TABLE order_new_db_10.t_order_0024(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0024';
//        CREATE TABLE order_new_db_10.t_order_0025(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0025';
//        CREATE TABLE order_new_db_10.t_order_0026(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0026';
//        CREATE TABLE order_new_db_10.t_order_0027(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0027';
//        CREATE TABLE order_new_db_10.t_order_0028(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0028';
//        CREATE TABLE order_new_db_10.t_order_0029(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0029';
//        CREATE TABLE order_new_db_10.t_order_0030(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0030';
//        CREATE TABLE order_new_db_10.t_order_0031(id bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键，订单id',order_no varchar(64) DEFAULT NULL COMMENT '订单号',name varchar(64) DEFAULT NULL COMMENT '名称',user_id bigint(20) DEFAULT NULL COMMENT '用户id',status varchar(64) DEFAULT NULL COMMENT '状态',create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '最后更新时间',PRIMARY KEY (id),KEY idx_createTime (create_time) USING BTREE) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8 COMMENT='t_order_0031';

    }
}
