spring:
  application:
    name: seata-demo-bank2
  main:
    allow-bean-definition-overriding: true
  datasource:
    ds0:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/deng?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      username: root
      password: root123456

server:
  port: 56081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:56080/eureka/

seata:
  enabled: true
  application-id: seata-demo-bank1
  #客户端和服务端在同一个事务组
  tx-service-group: my_test_tx_group

  ## https://blog.csdn.net/u010634066/article/details/106739176/
  enable-auto-data-source-proxy: true
  registry:
    type: eureka
    eureka:
      application: seata-demo-discovery
      service-url: http://localhost:56080/eureka
  config:
    type: file
