mysql:
  datasources:
    db1:
      type: org.apache.commons.dbcp2.BasicDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/deng?rewriteBatchedStatements=true&useUnicode=true&&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root123456
    db2:
      type: org.apache.commons.dbcp2.BasicDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/hu?rewriteBatchedStatements=true&useUnicode=true&&useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root123456
mybatis-plus:
  type-aliases-package: com.deng.jta.atomikos.xa.entity
  configuration:
    # 设置驼峰命名规则
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    com:
      deng:
        jta:
          atomikos:
            xa: DEBUG
