spring:
  application:
    name: seata-demo-account
  main:
    allow-bean-definition-overriding: true
  datasource:
    #ds0:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dtx_account?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root123456

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

server:
  port: 56082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:56080/eureka/

seata:
  enabled: true
  application-id: ${spring.application.name}
  #客户端和服务端在同一个事务组
  tx-service-group: my_test_tx_group