spring:
  application:
    name: dtx-seata-tcc-storage
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dtx_storage?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123456

dubbo:
  registry:
    address: nacos://127.0.0.1:8848
    protocol: nacos
    check: false
  protocol:
    name: dubbo
    port: 30881
  provider:
    timeout: 6000

server:
  port: 56083

seata:
  application-id: ${spring.application.name}
  tx-service-group: default_tx_group
  service:
    vgroup-mapping:
      default_tx_group: default-tx
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      namespace: public
      group: SEATA_GROUP
      cluster: default-tx
  enable-auto-data-source-proxy: false
