spring:
  application:
    name: tcc-demo-account
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dtx_amount?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
    username: root
    password: root123456

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

server:
  port: 56082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:56080/eureka/