spring:
  application:
    name: discover-server

server:
  port: 56080

eureka:
  instance:
    hostname: ${hostname:localhost}
    # 优先使用IP地址方式进行注册服务
    prefer-ip-address: true
    # 配置使用指定IP
    ip-address: 127.0.0.1
    # 每间隔2s，向服务端发送一次心跳，证明自己依然存活
    lease-renewal-interval-in-seconds: 2
    # 告诉服务端，如果当前客户端10s之内没有给服务端发心跳，就代表当前客户端故障了，可以将其剔除
    lease-expiration-duration-in-seconds: 10
  #    instance-id: ${spring.application.name}:${server.port}
  server:
    # 测试时关闭自我保护机制，保证不可用服务及时剔除
    enable-self-preservation: false
    # 清理无效节点的时间间隔，默认60000毫秒，也就是60秒
    eviction-interval-timer-in-ms: 20000
#    response-cache-update-interval-ms: 3000 #刷新
#    response-cache-auto-expiration-in-seconds: 180 #缓存
  client:
    # 默认情况下，这个应用会向注册中心（也是它自己）注册，由于我们目前创建的应用是一个服务注册中心，而不是普通的应用，
    # 所以设置为false表示禁止这种自己向自己注册的默认行为
    register-with-eureka: false
    # 表示不去从服务端检索其他服务信息，因为自己就是服务端，服务注册中心本身的职责就是维护服务实例，它不需要去检索其他服务
    fetch-registry: false
    service-url:
      # 指定服务注册中心的位置
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
