spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/deng?useUnicode=true&useSSL=false
          username: root
          password: root123456
        # 以 _ 分割的数据源名，首部为组名，相同组名称的数据源会放在一个组下
        slave_0:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/hu?useUnicode=true&useSSL=false
          username: root
          password: root123456
        slave_1:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/hu2?useUnicode=true&useSSL=false
          username: root
          password: root123456
        slave_2:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/hu3?useUnicode=true&useSSL=false
          username: root
          password: root123456

mybatis-plus:
  type-aliases-package: com.webbdong.readwritesplit.entity
  configuration:
    # 设置驼峰命名规则
    map-underscore-to-camel-case: true
