spring:
  application:
    name: tcc-demo-order
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dtx_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root123456

server:
  port: 56085

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

eureka:
  client:
    service-logging:
      level:
        com:
          webbdong:
            jtaatomikosxa:
              mapper: DEBUG:
      defaultZone: http://localhost:56080/eureka/

org:
  dromara:
    hmily:
      serializer: kryo
      recoverDelayTime: 128
      retryMax: 30
      scheduledDelay: 128
      scheduledThreadMax: 10
      repositorySupport: db
      started: true  # 服务调用方为true，其余为false
      hmilyDbConfig:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/dtx_order?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: root123456