spring:
  application:
    name: seata-demo-bank1
  main:
    allow-bean-definition-overriding: true
  datasource:
    ds0:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/deng?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT
      username: root
      password: root123456

server:
  port: 56082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:56080/eureka/

seata:
  enabled: true
  application-id: seata-bank1
  tx-service-group: seata_example_tx_group

  ## https://blog.csdn.net/u010634066/article/details/106739176/