server:
  port: 8091

spring:
  datasource:
    type: org.apache.commons.dbcp2.BasicDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/deng?useUnicode=true&useSSL=false
    username: root
    password: root123456

mybatis:
  ## 扫描当前包以及依赖包路径下的mapper.xml文件
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true